"""Bounded pure A3 input selection, structure, splitting, and handoff."""

from .codec import (
    MAX_TRIAGE_INPUT_BYTES,
    TRIAGE_INPUT_KIND,
    TRIAGE_INPUT_SCHEMA_VERSION,
    TriageInputCodec,
)
from .handoff import (
    PartExecution,
    SavedPartPayload,
    initial_part_states,
    saved_part_payloads,
    validate_parent_part_states,
)
from .models import (
    ContainerKind,
    CoverageFailure,
    FragmentKind,
    HeldReason,
    HeldSource,
    InputPart,
    InputPartReference,
    OccurrenceManifest,
    PartState,
    RepetitionPolicy,
    RepetitionTarget,
    SavedFilterBinding,
    SavedGroupBinding,
    SavedPreparedBinding,
    SavedRuleBinding,
    SemanticFragment,
    SourceRole,
    SourceRoleBinding,
    SplitBudget,
    TriageInputConfig,
    TriageInputSnapshot,
    TriageSelection,
    TrustedInputVersions,
    UnitManifest,
)
from .selection import TriageInputValidationError, validate_selection
from .snapshot import TriageInputBuildError, build_triage_input
from .split import (
    PART_KIND,
    PART_SCHEMA_VERSION,
    TriageInputSplitError,
    encode_part,
    validate_part_reference,
)

__all__ = [
    "MAX_TRIAGE_INPUT_BYTES",
    "PART_KIND",
    "PART_SCHEMA_VERSION",
    "TRIAGE_INPUT_KIND",
    "TRIAGE_INPUT_SCHEMA_VERSION",
    "ContainerKind",
    "CoverageFailure",
    "FragmentKind",
    "HeldReason",
    "HeldSource",
    "InputPart",
    "InputPartReference",
    "OccurrenceManifest",
    "PartExecution",
    "PartState",
    "RepetitionPolicy",
    "RepetitionTarget",
    "SavedFilterBinding",
    "SavedGroupBinding",
    "SavedPartPayload",
    "SavedPreparedBinding",
    "SavedRuleBinding",
    "SemanticFragment",
    "SourceRole",
    "SourceRoleBinding",
    "SplitBudget",
    "TriageInputBuildError",
    "TriageInputCodec",
    "TriageInputConfig",
    "TriageInputSnapshot",
    "TriageInputSplitError",
    "TriageInputValidationError",
    "TriageSelection",
    "TrustedInputVersions",
    "UnitManifest",
    "build_triage_input",
    "encode_part",
    "initial_part_states",
    "saved_part_payloads",
    "validate_parent_part_states",
    "validate_part_reference",
    "validate_selection",
]
