"""SQLAlchemy catalog models grouped by acquisition domain."""

from .acquisition import RawHttpEvidence, SourceBinding, SourceTargetBinding
from .base import Base
from .microsoft.onedrive import (
    OneDriveContentCapture,
    OneDriveContentRecord,
    OneDriveDeltaCheckpoint,
    OneDriveDeltaCheckpointCandidate,
    OneDriveDeltaResyncAttempt,
    OneDriveDeltaResyncObservation,
    OneDriveDriveRecord,
    OneDriveItemRecord,
)
from .microsoft.outlook import (
    AttachmentRecord,
    CalendarDeltaCheckpoint,
    CalendarDeltaCheckpointCandidate,
    CalendarDeltaEventState,
    CalendarDeltaObservation,
    CalendarEventAttachmentRecord,
    CalendarEventObservation,
    CalendarEventRecord,
    CalendarEventSighting,
    CalendarEventSurface,
    CalendarRecord,
    CalendarSeriesTopologyRecord,
    DeltaCheckpoint,
    DeltaCheckpointCandidate,
    FolderDeltaCheckpoint,
    FolderDeltaCheckpointCandidate,
    MailFolderPresence,
    MailFolderRecord,
    MailFolderSighting,
    MailFolderSnapshotCandidate,
    MessageObservation,
    MessagePresence,
    MessagePresenceCandidate,
    MessagePresenceSighting,
    MessageRecord,
    MessageSurface,
)
from .microsoft.todo import (
    TodoChecklistItemRecord,
    TodoLinkedResourceRecord,
    TodoTaskListRecord,
    TodoTaskRecord,
)

__all__ = [
    "AttachmentRecord",
    "Base",
    "CalendarDeltaCheckpoint",
    "CalendarDeltaCheckpointCandidate",
    "CalendarDeltaEventState",
    "CalendarDeltaObservation",
    "CalendarEventAttachmentRecord",
    "CalendarEventObservation",
    "CalendarEventRecord",
    "CalendarEventSighting",
    "CalendarEventSurface",
    "CalendarRecord",
    "CalendarSeriesTopologyRecord",
    "DeltaCheckpoint",
    "DeltaCheckpointCandidate",
    "FolderDeltaCheckpoint",
    "FolderDeltaCheckpointCandidate",
    "MailFolderPresence",
    "MailFolderRecord",
    "MailFolderSighting",
    "MailFolderSnapshotCandidate",
    "MessageObservation",
    "MessagePresence",
    "MessagePresenceCandidate",
    "MessagePresenceSighting",
    "MessageRecord",
    "MessageSurface",
    "OneDriveContentCapture",
    "OneDriveContentRecord",
    "OneDriveDeltaCheckpoint",
    "OneDriveDeltaCheckpointCandidate",
    "OneDriveDeltaResyncAttempt",
    "OneDriveDeltaResyncObservation",
    "OneDriveDriveRecord",
    "OneDriveItemRecord",
    "RawHttpEvidence",
    "SourceBinding",
    "SourceTargetBinding",
    "TodoChecklistItemRecord",
    "TodoLinkedResourceRecord",
    "TodoTaskListRecord",
    "TodoTaskRecord",
]
