"""SQLAlchemy catalog models grouped by acquisition domain."""

from .acquisition import RawHttpEvidence, SourceBinding, SourceTargetBinding
from .base import Base
from .microsoft.outlook import (
    AttachmentRecord,
    CalendarDeltaCheckpoint,
    CalendarDeltaCheckpointCandidate,
    CalendarDeltaEventState,
    CalendarDeltaObservation,
    CalendarEventAttachmentRecord,
    CalendarEventObservation,
    CalendarEventRecord,
    CalendarEventSighting,
    CalendarEventSurface,
    CalendarRecord,
    CalendarSeriesTopologyRecord,
    DeltaCheckpoint,
    DeltaCheckpointCandidate,
    FolderDeltaCheckpoint,
    FolderDeltaCheckpointCandidate,
    MailFolderPresence,
    MailFolderRecord,
    MailFolderSighting,
    MailFolderSnapshotCandidate,
    MessageObservation,
    MessagePresence,
    MessagePresenceCandidate,
    MessagePresenceSighting,
    MessageRecord,
    MessageSurface,
)

__all__ = [
    "AttachmentRecord",
    "Base",
    "CalendarDeltaCheckpoint",
    "CalendarDeltaCheckpointCandidate",
    "CalendarDeltaEventState",
    "CalendarDeltaObservation",
    "CalendarEventAttachmentRecord",
    "CalendarEventObservation",
    "CalendarEventRecord",
    "CalendarEventSighting",
    "CalendarEventSurface",
    "CalendarRecord",
    "CalendarSeriesTopologyRecord",
    "DeltaCheckpoint",
    "DeltaCheckpointCandidate",
    "FolderDeltaCheckpoint",
    "FolderDeltaCheckpointCandidate",
    "MailFolderPresence",
    "MailFolderRecord",
    "MailFolderSighting",
    "MailFolderSnapshotCandidate",
    "MessageObservation",
    "MessagePresence",
    "MessagePresenceCandidate",
    "MessagePresenceSighting",
    "MessageRecord",
    "MessageSurface",
    "RawHttpEvidence",
    "SourceBinding",
    "SourceTargetBinding",
]
