"""Provider-neutral preparation contracts."""

from msgloom.preparation.contracts import (
    BlockRole,
    CellLocation,
    DocumentFormat,
    DocumentLocation,
    LimitationKind,
    LinkBlock,
    MimePartLocation,
    MimePartReference,
    PageLocation,
    ParsedCell,
    ParsedLink,
    ParsedTable,
    ParserConfig,
    ParserIdentity,
    ParserLimitation,
    ParserLimits,
    ParserOutput,
    ParserProvenance,
    ParserRequest,
    SavedByteReference,
    SheetLocation,
    TableBlock,
    TextBlock,
)

__all__ = [
    "BlockRole",
    "CellLocation",
    "DocumentFormat",
    "DocumentLocation",
    "LimitationKind",
    "LinkBlock",
    "MimePartLocation",
    "MimePartReference",
    "PageLocation",
    "ParsedCell",
    "ParsedLink",
    "ParsedTable",
    "ParserConfig",
    "ParserIdentity",
    "ParserLimitation",
    "ParserLimits",
    "ParserOutput",
    "ParserProvenance",
    "ParserRequest",
    "SavedByteReference",
    "SheetLocation",
    "TableBlock",
    "TextBlock",
]
