"""Local acquisition catalog and its SQLAlchemy models."""

from message_ingest.catalog.models import (
    AttachmentRecord,
    Base,
    CalendarDeltaCheckpoint,
    CalendarDeltaCheckpointCandidate,
    CalendarDeltaEventState,
    CalendarDeltaObservation,
    CalendarEventAttachmentRecord,
    CalendarEventObservation,
    CalendarEventRecord,
    CalendarEventSighting,
    CalendarEventSurface,
    CalendarRecord,
    CalendarSeriesTopologyRecord,
    DeltaCheckpoint,
    DeltaCheckpointCandidate,
    FolderDeltaCheckpoint,
    FolderDeltaCheckpointCandidate,
    MailFolderPresence,
    MailFolderRecord,
    MailFolderSighting,
    MailFolderSnapshotCandidate,
    MessageObservation,
    MessagePresence,
    MessagePresenceCandidate,
    MessagePresenceSighting,
    MessageRecord,
    MessageSurface,
    RawHttpEvidence,
    SourceBinding,
    SourceTargetBinding,
    TodoChecklistItemRecord,
    TodoLinkedResourceRecord,
    TodoTaskListRecord,
    TodoTaskRecord,
)
from message_ingest.catalog.store import Catalog
from message_ingest.catalog.stores.evidence import RawEvidenceStore
from message_ingest.catalog.stores.microsoft.outlook import (
    OutlookCalendarStore,
    OutlookMailStore,
)
from message_ingest.catalog.stores.microsoft.todo import TodoStore

__all__ = [
    "AttachmentRecord",
    "Base",
    "CalendarDeltaCheckpoint",
    "CalendarDeltaCheckpointCandidate",
    "CalendarDeltaEventState",
    "CalendarDeltaObservation",
    "CalendarEventAttachmentRecord",
    "CalendarEventObservation",
    "CalendarEventRecord",
    "CalendarEventSighting",
    "CalendarEventSurface",
    "CalendarRecord",
    "CalendarSeriesTopologyRecord",
    "Catalog",
    "DeltaCheckpoint",
    "DeltaCheckpointCandidate",
    "FolderDeltaCheckpoint",
    "FolderDeltaCheckpointCandidate",
    "MailFolderPresence",
    "MailFolderRecord",
    "MailFolderSighting",
    "MailFolderSnapshotCandidate",
    "MessageObservation",
    "MessagePresence",
    "MessagePresenceCandidate",
    "MessagePresenceSighting",
    "MessageRecord",
    "MessageSurface",
    "OutlookCalendarStore",
    "OutlookMailStore",
    "RawEvidenceStore",
    "RawHttpEvidence",
    "SourceBinding",
    "SourceTargetBinding",
    "TodoChecklistItemRecord",
    "TodoLinkedResourceRecord",
    "TodoStore",
    "TodoTaskListRecord",
    "TodoTaskRecord",
]
